### ISSUE TITLE
Lineage from CaDeT

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/data-catalogue#13]
CaDeT can provide full lineage from source to derived table, but we don't have this working at the moment because we are only including a select list of tables.

This is controlled by the `node_name_pattern` which can have either an include list or an exclude list.

There is some low value tables that are created as part of the implementation of create_a_derived_table. Is there anyway we can exclude intermediate tables without losing the lineage either side of them?

Alternatively, can we ingest everything, but tag assets in such a way that we can filter out these intermediate tables from the search in find-moj-data? 

## Desired outcome of spike
- A working recipe we can use for dbt going forwards
- We are still able to hide intermediate tables from end users looking for data to use

**Comment by MatMoore** [comment]
Note: I briefly tried this node name pattern, but it seemed like it ruined the lineage

```yaml
        node_name_pattern:
            deny:
                - '.*intermediate'
                - '.*_intm_'
                - '.*_joined'
                - '.*_filtered'
                - '.*_stg_'
                - '.*_sensitive_'
```
