### ISSUE TITLE
Update CaDeT ingestion to process new metadata

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/data-catalogue#145]
Implement the approach from this spike https://github.com/ministryofjustice/find-moj-data/issues/363#issuecomment-2145169079

## What to do

- [x] Add the config below to the ingestion recipe
- [x] Also change the node name pattern to include all models
- [x] Merge https://github.com/moj-analytical-services/create-a-derived-table/pull/1568 to add default metadata for CaDeT to update

```yaml
    strip_user_ids_from_email: true
    tag_prefix: ""
    meta_mapping:
      owner_email:
        match: '.*'
        operation: 'add_owner'
        config:
          owner_type: user
          owner_category: DATAOWNER
```

Similar ticket to actually handle the new metadata fields: https://github.com/ministryofjustice/find-moj-data/issues/404

## Acceptance criteria
- [ ] We can run the CaDeT ingestion on dev and test without errors
- [ ] After running the ingestion, the new dc_* meta fields get set as custom properties in Datahub
- [ ] After running the ingestion, the new dc_display_in_catalogue tag gets set as a tag in Datahub
