### ISSUE TITLE
Populate DataHub instances with appropriate data

### ISSUE THREAD

**Issue by tom-webber** [ministryofjustice/data-catalogue#5]
We need to populate the different DataHub instances ([`Preprod`](https://datahub-catalogue-preprod.apps.live.cloud-platform.service.justice.gov.uk/), [`dev`](https://datahub-catalogue-dev.apps.live.cloud-platform.service.justice.gov.uk/), [`test`](https://datahub-catalogue-test.apps.live.cloud-platform.service.justice.gov.uk/)) with appropriate data. `Preprod` and `test` should contain copies of the data currently in `dev`.

## Definition of Done
- [ ] preprod DataHub instance populated
- [ ] test DataHub instance populated

**Comment by MatMoore** [comment]
Extract glossary terms from a datahub export json

```
jq '.[] | select(.entityType == "glossaryTerm") | [.entityUrn, .aspect.json.name, .aspect.json.definition, .aspect.json.parentNode] | @csv' datahub_export.json
```

**Comment by MatMoore** [comment]
I'll have to create the well documented view manually I think - can't see a way to export these.

I also had a look in datahub slack to see if anyones thought about a terraform provider for some of the data that is relatively static. There doesn't seem to be anything available at the moment, but there was some discussion about this about a year ago https://datahubspace.slack.com/archives/CUMUWQU66/p1635352024067800

**Comment by MatMoore** [comment]
## Notes for runbook
We have 3 datahub environments:
1. Dev (may be unstable if we are working on deployment)
2. Test (relatively stable, will be kept up to date as needed for user testing)
3. Pre-production (most stable, most out of date)

At least during alpha, all of these should be populated from the same sources of metadata, so that research participants are working with a catalogue that is as realistic as possible. This means there should be nothing important in our pre-production catalogue that is not also in the dev & test catalogues (including metadata from the production analytical platform).

### One-off ingestions
In each environment, we (the Data Catalogue team) have prepopulated a set of metadata that we have collated ourselves. This represents our current best guess at what good metadata may look like, and may form the basis of future ingestion post-alpha.

To repeat this process, follow the instructions in this repo: https://github.com/ministryofjustice/data-catalogue-metadata

When rerunning this, we expect the following to be created:
- Datasets and containers describing the Analytical Platform, based on the previous Data Discovery Tool
- Example data products - our best guess of what a well maintained data product will look like
- Our first draft of a glossary
- Our first draft of a domain model (to be replaced with one pulled from DBT) to organise the above
- A sample of users we have identified as possible data owners or custodians - and ownership associations to the datasets and data products above

### Scheduled ingestions
Each environment is configured with scheduled ingestions for metadata we expect to be updated. This demonstrates how we can continually **pull** data from other parts of the MOJ estate.

These sources are configured from the ingestion tab in Datahub.

We should have ingestion sources for the following:
- DBT ingestion for Create a derived table. This brings in derived tables and their lineage. Source tables *may* overlap with those ingested from other sources.
- Custom ingestion for Justice Data charts (currently untested)

Note that the ingestion tab may also show ingestions triggered from the command line, although these will show up as view-only and cannot be triggered again from the UI.

### Manually controlled
Certain aspects of the environment are not reproducable from code. These include

- Setting a warning notice on the datahub homepage
- Creating custom views in datahub, e.g. "Well documented data"

These must be set up manually when recreating an environment.

**Comment by MatMoore** [comment]
Our previous DBT config used a presigned s3 url to access the manifest. This time round we would like to try 
- populating via s3 using an assumed role
- broadening the list of tables we pull in

```yaml
source:
    type: dbt
    config:

        # insert s3 path here

        target_platform: s3
        entities_enabled:
            test_results: No
            seeds: No
            snapshots: No
            models: Yes
            sources: No
            test_definitions: No
        node_name_pattern:
            allow:
                - '.*oasys_set$'
                - '.*oasys_section$'
                - '.*oasys_question$'
                - '.*oasys_answer$'
                - '.*oasys_assessment_group$'
                - '.*offender$'
                - '.*ref_question$'
                - '.*prison_population_history__imprisonment_spells$'
                - '.*prison_population_history__jicsl_lookup_ao_population_nart$'
                - '.*derived_delius__components_at_latest$'
                - '.*derived_delius__components_at_comm$'
                - '.*derived_delius__components_at_term$'
                - '.*derived_delius__contacts$'
                - '.*derived_delius__court_appearances$'
                - '.*derived_delius__court_reports$'
                - '.*derived_delius__first_release$'
                - '.*derived_delius__releases$'
                - '.*derived_delius__sentences_at_disp$'
                - '.*derived_delius__sentences_at_latest$'
                - '.*derived_delius__sentences_at_term$'
                - '.*derived_delius__upw_appointments$'
                - '.*common_platform_derived__all_offence_fct$'
                - '.*common_platform_derived__cases_fct$'
                - '.*common_platform_derived__crown_trials_fct$'
                - '.*common_platform_derived__def_hearing_summary_fct$'
                - '.*common_platform_derived__defendant_summary_fct$'
                - '.*common_platform_derived__disposal_summary_fct$'
                - '.*common_platform_derived__sjp_all_offence_fct$'
                - '.*common_platform_derived__sjp_defendant_summary_fct$'
                - '.*common_platform_derived__sjp_disposal_summary_fct$'
                - '.*common_platform_derived__sjp_session_summary_fct$'
                - '.*lookup_offence_v2__cjs_offence_code_to_ho_offence_code$'
                - '.*lookup_offence_v2__ho_offence_codes$'
                - '.*lookup_offence_v2__offence_group$'
                - '.*lookup_offence_v2__offence_group_code$'
                - '.*lookup_offence_v2__offence_priority$'
        stateful_ingestion:
            remove_stale_metadata: true

```

**Comment by MatMoore** [comment]
Modified version for running on test.

I haven't set this up as a scheduled task yet - but we can try this once https://github.com/moj-analytical-services/create-a-derived-table/pull/1269 is merged

```
source:
    type: dbt
    config:
        platform_instance: create_a_derived_table
        manifest_path: 'manifest.json'
        catalog_path: 'catalog.json'
        target_platform: athena
        entities_enabled:
            test_results: 'NO'
            seeds: 'NO'
            snapshots: 'NO'
            models: 'YES'
            sources: 'NO'
            test_definitions: 'NO'
        node_name_pattern:
            allow:
                - '.*oasys_set$'
                - '.*oasys_section$'
                - '.*oasys_question$'
                - '.*oasys_answer$'
                - '.*oasys_assessment_group$'
                - '.*offender$'
                - '.*ref_question$'
                - '.*prison_population_history__imprisonment_spells$'
                - '.*prison_population_history__jicsl_lookup_ao_population_nart$'
                - '.*derived_delius__components_at_latest$'
                - '.*derived_delius__components_at_comm$'
                - '.*derived_delius__components_at_term$'
                - '.*derived_delius__contacts$'
                - '.*derived_delius__court_appearances$'
                - '.*derived_delius__court_reports$'
                - '.*derived_delius__first_release$'
                - '.*derived_delius__releases$'
                - '.*derived_delius__sentences_at_disp$'
                - '.*derived_delius__sentences_at_latest$'
                - '.*derived_delius__sentences_at_term$'
                - '.*derived_delius__upw_appointments$'
                - '.*common_platform_derived__all_offence_fct$'
                - '.*common_platform_derived__cases_fct$'
                - '.*common_platform_derived__crown_trials_fct$'
                - '.*common_platform_derived__def_hearing_summary_fct$'
                - '.*common_platform_derived__defendant_summary_fct$'
                - '.*common_platform_derived__disposal_summary_fct$'
                - '.*common_platform_derived__sjp_all_offence_fct$'
                - '.*common_platform_derived__sjp_defendant_summary_fct$'
                - '.*common_platform_derived__sjp_disposal_summary_fct$'
                - '.*common_platform_derived__sjp_session_summary_fct$'
                - '.*lookup_offence_v2__cjs_offence_code_to_ho_offence_code$'
                - '.*lookup_offence_v2__ho_offence_codes$'
                - '.*lookup_offence_v2__offence_group$'
                - '.*lookup_offence_v2__offence_group_code$'
                - '.*lookup_offence_v2__offence_priority$'
        stateful_ingestion:
            remove_stale_metadata: true

sink:
  type: datahub-rest
  config:
    server: "https://datahub-catalogue-test.apps.live.cloud-platform.service.justice.gov.uk/api/gms"
    token: xxxx
```
